require(knitr)
require(markdown)
setwd("/Users/magnuskristensen/Desktop/Documents/Coursera/Getting and Cleaning Data/Week 4")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")