<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Preliminaries</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>

<!-- MathJax scripts -->
<script type="text/javascript" src="https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<p>The data set (Human Activity Recognition Using Smartphones) is from the <a href="http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones">UCI Machine Learning Repository</a>. Information about the data file can be found in README.txt, features.txt and features_info.txt, and any changes to the data file will be described here.<br></p>

<h2>Preliminaries</h2>

<p>Load packages.</p>

<pre><code class="r">library(data.table)
</code></pre>

<pre><code>## data.table 1.10.4
</code></pre>

<pre><code>##   The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
</code></pre>

<pre><code>##   Documentation: ?data.table, example(data.table) and browseVignettes(&quot;data.table&quot;)
</code></pre>

<pre><code>##   Release notes, videos and slides: http://r-datatable.com
</code></pre>

<p>Set path.</p>

<pre><code class="r">path &lt;- getwd()
</code></pre>

<h2>Part 1</h2>

<p><strong>Merge the training and the test sets to create one data set.</strong><br></p>

<h3>Read the files</h3>

<p>Let&#39;s start off by getting the activity data into R by downloading and unzipping the file. A URL for the data is provided on the course homepage.</p>

<pre><code class="r">fileUrl &lt;- &quot;https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip&quot;

if (!file.exists(&quot;./UCI HAR Dataset.zip&quot;)) {
      download.file(fileUrl, destfile = &quot;./UCI HAR Dataset.zip&quot;, method = &quot;curl&quot;)
      }

if (!file.exists(&quot;./UCI HAR Dataset&quot;)) unzip(&quot;./UCI HAR Dataset.zip&quot;, exdir = &quot;./&quot;)
</code></pre>

<p>The archive put the files in a folder named <strong>UCI HAR Dataset</strong>. Let&#39;s see what this folder contains. </p>

<pre><code class="r">pathIn &lt;- file.path(path, &quot;UCI HAR Dataset&quot;)
list.files(pathIn, recursive = TRUE)
</code></pre>

<pre><code>##  [1] &quot;activity_labels.txt&quot;                         
##  [2] &quot;features_info.txt&quot;                           
##  [3] &quot;features.txt&quot;                                
##  [4] &quot;README.txt&quot;                                  
##  [5] &quot;test/Inertial Signals/body_acc_x_test.txt&quot;   
##  [6] &quot;test/Inertial Signals/body_acc_y_test.txt&quot;   
##  [7] &quot;test/Inertial Signals/body_acc_z_test.txt&quot;   
##  [8] &quot;test/Inertial Signals/body_gyro_x_test.txt&quot;  
##  [9] &quot;test/Inertial Signals/body_gyro_y_test.txt&quot;  
## [10] &quot;test/Inertial Signals/body_gyro_z_test.txt&quot;  
## [11] &quot;test/Inertial Signals/total_acc_x_test.txt&quot;  
## [12] &quot;test/Inertial Signals/total_acc_y_test.txt&quot;  
## [13] &quot;test/Inertial Signals/total_acc_z_test.txt&quot;  
## [14] &quot;test/subject_test.txt&quot;                       
## [15] &quot;test/X_test.txt&quot;                             
## [16] &quot;test/y_test.txt&quot;                             
## [17] &quot;train/Inertial Signals/body_acc_x_train.txt&quot; 
## [18] &quot;train/Inertial Signals/body_acc_y_train.txt&quot; 
## [19] &quot;train/Inertial Signals/body_acc_z_train.txt&quot; 
## [20] &quot;train/Inertial Signals/body_gyro_x_train.txt&quot;
## [21] &quot;train/Inertial Signals/body_gyro_y_train.txt&quot;
## [22] &quot;train/Inertial Signals/body_gyro_z_train.txt&quot;
## [23] &quot;train/Inertial Signals/total_acc_x_train.txt&quot;
## [24] &quot;train/Inertial Signals/total_acc_y_train.txt&quot;
## [25] &quot;train/Inertial Signals/total_acc_z_train.txt&quot;
## [26] &quot;train/subject_train.txt&quot;                     
## [27] &quot;train/X_train.txt&quot;                           
## [28] &quot;train/y_train.txt&quot;
</code></pre>

<p>In this part of the assignment, we are asked to merge the training and the test sets to create one data set. The relevant factors are:</p>

<ul>
<li>X_test/train is the test/training set.</li>
<li>Y_test/train is the test/training labels.</li>
<li>subject_test/train is used to identify the subject who performed a given task.</li>
<li>Features is a list of the measured features.</li>
<li>Activity links the class labels with their activity name.</li>
</ul>

<p>Read the subject files.</p>

<pre><code class="r">SubjectTest &lt;-read.table(&quot;UCI HAR Dataset/test/subject_test.txt&quot;)
SubjectTrain &lt;-read.table(&quot;UCI HAR Dataset/train/subject_train.txt&quot;)
</code></pre>

<p>Read the activity files.</p>

<pre><code class="r">ActivityTest&lt;- read.table(&quot;UCI HAR Dataset/test/Y_test.txt&quot;)
ActivityTrain&lt;- read.table(&quot;UCI HAR Dataset/train/Y_train.txt&quot;)
</code></pre>

<p>Read the data files.</p>

<pre><code class="r">DataTest&lt;- read.table(&quot;UCI HAR Dataset/test/X_test.txt&quot;)
DataTrain&lt;- read.table(&quot;UCI HAR Dataset/train/X_train.txt&quot;)
</code></pre>

<h3>Merging the training and the test sets</h3>

<pre><code class="r">## Merging and renaming activity
activity &lt;- rbind(ActivityTest, ActivityTrain)
setnames(activity, &quot;V1&quot;, &quot;activityNumber&quot;)

## Merging and renaming subject
subject &lt;- rbind(SubjectTest, SubjectTrain)
setnames(subject, &quot;V1&quot;, &quot;subject&quot;)

## Merging data
data &lt;- rbind(DataTest, DataTrain)
data &lt;- cbind(subject, activity, data)

## Convert the data.frame to a data.table.
setDT(data)
setkey(data, subject, activityNumber)
</code></pre>

<p>The dimensions of the new data sets are:</p>

<pre><code class="r">dim(data)
</code></pre>

<pre><code>## [1] 10299   563
</code></pre>

<p>As of now, we see that the data contains 10299 observations on 563 variables. Let&#39;s reduce these numbers a little.</p>

<h2>Part 2</h2>

<p><strong>Extract only the measurements on the mean and standard deviation for each measurement.</strong><br></p>

<p>To accomplish this, we use the <em>grep</em> function to get only the features indeces which contain <strong>mean()</strong> or <strong>std()</strong> in their name. Read the <em>features.txt</em> file.</p>

<pre><code class="r">features &lt;- fread(file.path(pathIn, &quot;features.txt&quot;))
setnames(features, names(features), c(&quot;featureNumber&quot;, &quot;featureName&quot;))
</code></pre>

<p>Now we subset for only the measurements of mean and std.</p>

<pre><code class="r">features &lt;- features[grepl(&quot;mean\\(\\)|std\\(\\)&quot;, featureName)]
</code></pre>

<p>If we take a look at the features, we notice that they are labeled only by featurenumber (integer) whereas the names in data all start with V(integer). Let&#39;s match the two files by supplying a featureCode to <em>features</em> and view the result.</p>

<pre><code class="r">features$featureCode &lt;- features[, paste0(&quot;V&quot;, featureNumber)]
head(features)
</code></pre>

<pre><code>##    featureNumber       featureName featureCode
## 1:             1 tBodyAcc-mean()-X          V1
## 2:             2 tBodyAcc-mean()-Y          V2
## 3:             3 tBodyAcc-mean()-Z          V3
## 4:             4  tBodyAcc-std()-X          V4
## 5:             5  tBodyAcc-std()-Y          V5
## 6:             6  tBodyAcc-std()-Z          V6
</code></pre>

<p>We can now use the list of desired features to subset the data.</p>

<pre><code class="r">selectData &lt;- c(key(data), features$featureCode)
data &lt;- data[, selectData, with = FALSE]
</code></pre>

<h2>Part 3</h2>

<p><strong>Use descriptive activity names to name the activities in the data set.</strong></p>

<p>The descriptive activity names can be found in <strong>activity_labels.txt</strong> from the zip file, so lets start by importing those.</p>

<pre><code class="r">activityName &lt;- fread(file.path(pathIn, &quot;activity_labels.txt&quot;))
setnames(activityName, names(activityName), c(&quot;activityNumber&quot;, &quot;activityName&quot;))
</code></pre>

<p>The variable now <strong>activity_labels</strong> contains the descriptive names, so let&#39;s merge these with the data. We can use the <em>activityNumber</em> as a reference between the two.</p>

<pre><code class="r">data &lt;- merge(data, activityName, by = &quot;activityNumber&quot;, all.x = TRUE)
setkey(data, subject, activityNumber, activityName)
</code></pre>

<h2>Part 4</h2>

<p><strong>Appropriately label the data set with descriptive variable names.</strong></p>

<p>This is all well and good, but the data variable still has 66 variables, and is by no means &ldquo;tidy&rdquo; yet. As an example, there are several instances of seperate colums for an X, Y and Z variable. Let&#39;s reshape and melt the data to make it tidy. In the previous line of code, we set a key to let R now how we would like to reshape the data.</p>

<pre><code class="r">data &lt;- data.table(melt(data, key(data), variable.name = &quot;featureCode&quot;))
</code></pre>

<p>Now, include the activity names, using the featureCode as a reference.</p>

<pre><code class="r">data &lt;- merge(data, features[, list(featureNumber, featureCode, featureName)], by = &quot;featureCode&quot;, 
    all.x = TRUE)
</code></pre>

<p>Let&#39;s have a look at the data:</p>

<pre><code class="r">head(data)
</code></pre>

<pre><code>##    featureCode subject activityNumber activityName     value featureNumber
## 1:          V1       1              1      WALKING 0.2820216             1
## 2:          V1       1              1      WALKING 0.2558408             1
## 3:          V1       1              1      WALKING 0.2548672             1
## 4:          V1       1              1      WALKING 0.3433705             1
## 5:          V1       1              1      WALKING 0.2762397             1
## 6:          V1       1              1      WALKING 0.2554682             1
##          featureName
## 1: tBodyAcc-mean()-X
## 2: tBodyAcc-mean()-X
## 3: tBodyAcc-mean()-X
## 4: tBodyAcc-mean()-X
## 5: tBodyAcc-mean()-X
## 6: tBodyAcc-mean()-X
</code></pre>

<p>Excellent. But now we notice that the featureName(s) actually is a cover for several different variables. Not tidy at all. E.g. the first element of <em>featureName</em> is &ldquo;tBodyAcc-mean()-X&rdquo; which tells us that we are looking at time, acceleration and mean for a measurement on the X axis performed on the body. We would like to split these into seperate variables.<br></p>

<p>To split the data.table we create two new variables as a factor class. <strong>activity</strong> is equivalent to <strong>activityName</strong> and <strong>feature</strong> is equivalent to <strong>featureName</strong> (but this time as factors).</p>

<pre><code class="r">data$activity &lt;- factor(data$activityName)
data$feature &lt;- factor(data$featureName)
</code></pre>

<p>From a call to <strong>unique(data[ ,featureName])</strong> we see that the <em>featureName</em> covers the variables:</p>

<p>1) <strong>t</strong> or <strong>f</strong> for time or frequency.
2) <strong>Acc</strong> or <strong>Gyro</strong> for accelerometer or gyroscope.
3) <strong>Body</strong> or <strong>Gravity</strong> for measurement on the body or gravity.
4) <strong>mean()</strong> or <strong>std()</strong> for mean or standard deviation. 
5) <strong>Jerk</strong>. Body linear acceleration and angular velocity were derived in time to obtain Jerk signals.
6) <strong>Mag</strong> for magnitude of the three-dimensional signals.
7) <strong>-X</strong>, <strong>-Y</strong>, <strong>-Z</strong> to indicate the axis of measurement. We include the &ldquo;-&rdquo; to avoid that random capital X, Y or Z are mistaken for an axis.</p>

<p>To extract all of these properties from the featureName, we  will use a helper function to avoid some excess typing. The helper function seperates features from <em>data$feature</em>.</p>

<pre><code class="r">grepFeature &lt;- function(regex) grepl(regex, data$feature)
</code></pre>

<p>Let&#39;s use this function. Notice that the features in the list above can have either one, two or three different outcomes and hence the code to relabel will be a little bit different depending on the number of outcomes. In all instances we create a new variable in the data.table to account for the given variable.<br></p>

<p>Features with one category:</p>

<pre><code class="r">## Jerk and Magnitude.
data$jerk &lt;- factor(grepFeature(&quot;Jerk&quot;), labels = c(NA, &quot;Jerk&quot;))
data$magnitude &lt;- factor(grepFeature(&quot;Mag&quot;), labels = c(NA, &quot;Magnitude&quot;))
</code></pre>

<p>Features with two categories. Create a vector to hold the categories.</p>

<pre><code class="r">n &lt;- 2
numberOfCategories &lt;- matrix(seq(1, n), nrow = n)

## Time or frequency.
categories &lt;- matrix(c(grepFeature(&quot;^t&quot;), grepFeature(&quot;^f&quot;)), ncol = nrow(numberOfCategories))
data$domain &lt;- factor(categories %*% numberOfCategories, labels = c(&quot;Time&quot;, &quot;Freq&quot;))

## Accelerometer or gyroscope.
categories &lt;- matrix(c(grepFeature(&quot;Acc&quot;), grepFeature(&quot;Gyro&quot;)), ncol = nrow(numberOfCategories))
data$instrument &lt;- factor(categories %*% numberOfCategories, labels = c(&quot;Accelerometer&quot;, &quot;Gyroscope&quot;))

## Body or gravity.
categories &lt;- matrix(c(grepFeature(&quot;BodyAcc&quot;), grepFeature(&quot;GravityAcc&quot;)), ncol = nrow(numberOfCategories))
data$acceleration &lt;- factor(categories %*% numberOfCategories, labels = c(NA, &quot;Body&quot;, &quot;Gravity&quot;))

## Mean or standard deviation.
categories &lt;- matrix(c(grepFeature(&quot;mean()&quot;), grepFeature(&quot;std()&quot;)), ncol = nrow(numberOfCategories))
data$variable &lt;- factor(categories %*% numberOfCategories, labels = c(&quot;Mean&quot;, &quot;Std&quot;))
</code></pre>

<p>Features with three categories:</p>

<pre><code class="r">n &lt;- 3
numberOfCategories &lt;- matrix(seq(1, n), nrow = n)

categories &lt;- matrix(c(grepFeature(&quot;-X&quot;), grepFeature(&quot;-Y&quot;), grepFeature(&quot;-Z&quot;)), ncol = nrow(numberOfCategories))
data$axis &lt;- factor(categories %*% numberOfCategories, labels = c(NA, &quot;X&quot;, &quot;Y&quot;, &quot;Z&quot;))
</code></pre>

<h2>Part 5</h2>

<p><strong>From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject.</strong></p>

<p>Finally we create the tidy data set, with the average of each variable for each activity and each subject.</p>

<pre><code class="r">setkey(data, subject, activity, domain, acceleration, instrument, jerk, magnitude, variable, axis)
tidyData &lt;- data[, list(count = .N, average = mean(value)), by = key(data)]
</code></pre>

<p>&hellip; and just for the fun of it, let&#39;s have a look at what we have obtained:</p>

<pre><code class="r">head(tidyData)
</code></pre>

<pre><code>##    subject activity domain acceleration instrument jerk magnitude variable
## 1:       1   LAYING   Time           NA  Gyroscope   NA        NA     Mean
## 2:       1   LAYING   Time           NA  Gyroscope   NA        NA     Mean
## 3:       1   LAYING   Time           NA  Gyroscope   NA        NA     Mean
## 4:       1   LAYING   Time           NA  Gyroscope   NA        NA      Std
## 5:       1   LAYING   Time           NA  Gyroscope   NA        NA      Std
## 6:       1   LAYING   Time           NA  Gyroscope   NA        NA      Std
##    axis count     average
## 1:    X    50 -0.01655309
## 2:    Y    50 -0.06448612
## 3:    Z    50  0.14868944
## 4:    X    50 -0.87354387
## 5:    Y    50 -0.95109044
## 6:    Z    50 -0.90828466
</code></pre>

<p>The last few lines are just practicallities for creating the CodeBook for this project.</p>

<pre><code class="r">knit(&quot;MakeCodeBook.rmd&quot;, output = &quot;CodeBook.md&quot;)
</code></pre>

<pre><code>## 
## 
## processing file: MakeCodeBook.rmd
</code></pre>

<pre><code>## 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |......                                                           |  10%
##   ordinary text without R code
## 
## 
  |                                                                       
  |.............                                                    |  20%
## label: unnamed-chunk-27
## 
  |                                                                       
  |....................                                             |  30%
##   ordinary text without R code
## 
## 
  |                                                                       
  |..........................                                       |  40%
## label: unnamed-chunk-28
## 
  |                                                                       
  |................................                                 |  50%
##   ordinary text without R code
## 
## 
  |                                                                       
  |.......................................                          |  60%
## label: unnamed-chunk-29
## 
  |                                                                       
  |..............................................                   |  70%
##   ordinary text without R code
## 
## 
  |                                                                       
  |....................................................             |  80%
## label: unnamed-chunk-30
## 
  |                                                                       
  |..........................................................       |  90%
##   ordinary text without R code
## 
## 
  |                                                                       
  |.................................................................| 100%
## label: unnamed-chunk-31
</code></pre>

<pre><code>## output file: CodeBook.md
</code></pre>

<pre><code>## [1] &quot;CodeBook.md&quot;
</code></pre>

<pre><code class="r">markdownToHTML(&quot;CodeBook.md&quot;, &quot;CodeBook.html&quot;)
</code></pre>

</body>

</html>
